[package]
name = "sea-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Procedural macros for the searepo crate"

[lib]
proc-macro = true

[dependencies]
syn = { version = "3.0.6", features = ["full", "extra-traits"] }
quote = "1.0.47"
proc-macro2 = "1.0.107"
